# development:
#   cloud_name: "dgws79ntj"
#   api_key: "465367466432226"
#   api_secret: "eQ9iYMuofjLv7oURnabi5SK5IIM"

production:
  cloud_name: "ht7agebhwj"
  api_key: "422155845298185"
  api_secret: "75j_FE3Ff94fGrm608_m8q4znu4"